unit DAServer_Invk;

// ----------------------------------------------------------------------
//  This file was automatically generated by Remoting SDK from a
//  RODL file downloaded from a server or associated with this project.
//
//  Do not modify this file manually, or your changes will be lost when
//  it is regenerated the next time you update your RODL.
// ----------------------------------------------------------------------

{$I RemObjects.inc}

interface

uses
  {$IFDEF DELPHIXE2UP}System.SysUtils{$ELSE}SysUtils{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.Classes{$ELSE}Classes{$ENDIF},
  uROEncoding,
  uROXMLIntf,
  uROServer,
  uROServerIntf,
  uROClasses,
  uROTypes,
  uROClientIntf,
  DataAbstract4_Intf,
  DataAbstract4_Invk,
  DAServer_Intf;

type
  { Forward declarations }
  TDataService_Invoker = class;

  TDataService_Invoker = class(DataAbstract4_invk.TDataAbstractService_Invoker)
  public
    constructor Create; override;
  end;

implementation

uses
  uROSystem,
  uROEventRepository,
  uRORes,
  uROClient;

constructor TDataService_Invoker.Create;
begin
  inherited Create();
  FAbstract := false;
end;

initialization
finalization
end.

